<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Final Project – Vansh Setpal</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Vansh Setpal</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./portfolio.html"> 
<span class="menu-text">Mid Project</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./blog.html"> 
<span class="menu-text">Video</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./code.html"> 
<span class="menu-text">Codes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./FinalProject.html" aria-current="page"> 
<span class="menu-text">Final Project</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#supply-chain-analytics-using-statistical-methods" id="toc-supply-chain-analytics-using-statistical-methods" class="nav-link active" data-scroll-target="#supply-chain-analytics-using-statistical-methods">Supply Chain Analytics Using Statistical Methods</a>
  <ul class="collapse">
  <li><a href="#team-members---vansh-setpal-neha-rao-and-vaibhav-hasu" id="toc-team-members---vansh-setpal-neha-rao-and-vaibhav-hasu" class="nav-link" data-scroll-target="#team-members---vansh-setpal-neha-rao-and-vaibhav-hasu">Team Members - Vansh Setpal, Neha Rao and Vaibhav Hasu</a></li>
  <li><a href="#dataset" id="toc-dataset" class="nav-link" data-scroll-target="#dataset">Dataset</a></li>
  <li><a href="#data-cleaning" id="toc-data-cleaning" class="nav-link" data-scroll-target="#data-cleaning">Data Cleaning</a></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions">Research Questions</a>
  <ul class="collapse">
  <li><a href="#q1.-what-factors-contribute-to-the-prediction-of-insurance-costs-in-supply-chain-shipments" id="toc-q1.-what-factors-contribute-to-the-prediction-of-insurance-costs-in-supply-chain-shipments" class="nav-link" data-scroll-target="#q1.-what-factors-contribute-to-the-prediction-of-insurance-costs-in-supply-chain-shipments">Q1. What factors contribute to the prediction of insurance costs in supply chain shipments?</a></li>
  <li><a href="#q2.-how-can-we-classify-shipments-into-low-medium-and-high-insurance-cost-categories" id="toc-q2.-how-can-we-classify-shipments-into-low-medium-and-high-insurance-cost-categories" class="nav-link" data-scroll-target="#q2.-how-can-we-classify-shipments-into-low-medium-and-high-insurance-cost-categories">Q2. How can we classify shipments into “low”, “medium” and “high” insurance cost categories?</a></li>
  <li><a href="#q3.-what-are-the-key-factors-influencing-delivery-outcomes-and-how-accurately-can-delivery-categories-be-predicted-using-shipment-features" id="toc-q3.-what-are-the-key-factors-influencing-delivery-outcomes-and-how-accurately-can-delivery-categories-be-predicted-using-shipment-features" class="nav-link" data-scroll-target="#q3.-what-are-the-key-factors-influencing-delivery-outcomes-and-how-accurately-can-delivery-categories-be-predicted-using-shipment-features">Q3. What are the key factors influencing delivery outcomes and how accurately can delivery categories be predicted using shipment features?</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Final Project</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="supply-chain-analytics-using-statistical-methods" class="level1">
<h1>Supply Chain Analytics Using Statistical Methods</h1>
<section id="team-members---vansh-setpal-neha-rao-and-vaibhav-hasu" class="level2">
<h2 class="anchored" data-anchor-id="team-members---vansh-setpal-neha-rao-and-vaibhav-hasu">Team Members - Vansh Setpal, Neha Rao and Vaibhav Hasu</h2>
</section>
<section id="dataset" class="level2">
<h2 class="anchored" data-anchor-id="dataset">Dataset</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      id project.code           pq..   po...so..  asn.dn..       country
19 81483   108-VN-T30      FPQ-10286 SCMS-156150 ASN-16914       Vietnam
21    92   102-NG-T01 Pre-PQ Process    SCMS-592   ASN-485       Nigeria
23   108   104-CI-T01 Pre-PQ Process    SCMS-698   ASN-727 Côte d'Ivoire
24   115   108-VN-T01 Pre-PQ Process    SCMS-753   ASN-781       Vietnam
25   116   108-VN-T01 Pre-PQ Process    SCMS-759   ASN-632       Vietnam
26   130   100-HT-T01 Pre-PQ Process  SCMS-10080   ASN-628         Haiti
   managed.by fulfill.via vendor.inco.term shipment.mode
19   PMO - US Direct Drop              EXW           Air
21   PMO - US Direct Drop              EXW           Air
23   PMO - US Direct Drop              CIP           Air
24   PMO - US Direct Drop              EXW           Air
25   PMO - US Direct Drop              FCA           Air
26   PMO - US Direct Drop              EXW           Air
   pq.first.sent.to.client.date po.sent.to.vendor.date scheduled.delivery.date
19                    7/25/2012              8/15/2012               12-Nov-12
21               Pre-PQ Process              5/13/2007               19-Jun-07
23               Pre-PQ Process              7/13/2007                2-Oct-07
24               Pre-PQ Process               7/4/2007               15-Oct-07
25               Pre-PQ Process               7/4/2007               27-Aug-07
26               Pre-PQ Process              7/26/2007               13-Aug-07
   delivered.to.client.date delivery.recorded.date product.group
19                12-Nov-12              12-Nov-12           ARV
21                19-Jun-07              19-Jun-07          HRDT
23                 2-Oct-07               2-Oct-07           ARV
24                15-Oct-07              15-Oct-07           ARV
25                27-Aug-07              27-Aug-07           ARV
26                21-Aug-07              21-Aug-07          HRDT
   sub.classification                                          vendor
19              Adult                                   CIPLA LIMITED
21           HIV test                            Abbott GmbH &amp; Co. KG
23          Pediatric                            BRISTOL-MYERS SQUIBB
24          Pediatric                        Aurobindo Pharma Limited
25              Adult ABBVIE LOGISTICS (FORMERLY ABBOTT LOGISTICS BV)
26           HIV test                                   Orgenics, Ltd
                                           item.description
19                       Zidovudine 300mg, tablets, 60 Tabs
21           HIV 1/2, Determine Complete HIV Kit, 100 Tests
23      #102198**Didanosine 200mg [Videx], tablets, 60 Tabs
24      Nevirapine 10mg/ml, oral suspension, Bottle, 240 ml
25 Lopinavir/Ritonavir 200/50mg [Aluvia], tablets, 120 Tabs
26   HIV 1/2, Determine HIV Kit, without Lancets, 100 Tests
                            molecule.test.type     brand   dosage
19                                  Zidovudine   Generic    300mg
21         HIV 1/2, Determine Complete HIV Kit Determine         
23                                  Didanosine     Videx    200mg
24                                  Nevirapine   Generic  10mg/ml
25                         Lopinavir/Ritonavir    Aluvia 200/50mg
26 HIV 1/2, Determine HIV Kit, without Lancets Determine         
       dosage.form unit.of.measure..per.pack. line.item.quantity
19          Tablet                         60                525
21        Test kit                        100               1000
23          Tablet                         60               5513
24 Oral suspension                        240               1000
25          Tablet                        120                500
26        Test kit                        100                750
   line.item.value pack.price unit.price            manufacturing.site
19          3465.0       6.60       0.11             Cipla, Goa, India
21         80000.0      80.00       0.80 ABBVIE GmbH &amp; Co.KG Wiesbaden
23        140581.5      25.50       0.42            BMS Meymac, France
24          1920.0       1.92       0.01     Aurobindo Unit III, India
25         41095.0      82.19       0.68   ABBVIE Ludwigshafen Germany
26         53992.5      71.99       0.72               Inverness Japan
   first.line.designation weight..kilograms.                 freight.cost..usd.
19                   true                 34                             807.47
21                   true                341                            2682.47
23                   true               2126 Freight Included in Commodity Cost
24                   true                941                            4193.49
25                   true                117                            1767.38
26                   true                171                            3518.38
   line.item.insurance..usd. freight_cost_usd weight_kilograms
19                      4.86          807.470               34
21                    128.00         2682.470              341
23                    224.93         5869.655             2126
24                      3.07         4193.490              941
25                     65.75         1767.380              117
26                     86.39         3518.380              171</code></pre>
</div>
</div>
<p>The dataset focuses on supply chain operations, capturing details about shipments, associated costs, and product characteristics. Key variables include freight_cost_usd, representing freight costs in USD, and line.item.insurance..usd., indicating the insurance cost for line items. Shipment details such as the shipment.mode (e.g., air, sea, or road) and the destination country are included, alongside product-related variables like product.group, sub.classification, line.item.quantity, and line.item.value. Additionally, weight_kilograms captures the shipment weight, while pack.price provides the price per package. The dataset includes both numerical and categorical variables, requiring preprocessing to ensure consistency and readiness for analysis.</p>
</section>
<section id="data-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="data-cleaning">Data Cleaning</h2>
<p>The dataset underwent extensive cleaning steps to ensure quality and usability for analysis. Non-numeric entries in <code>freight.cost..usd.</code> and <code>weight..kilograms.</code> were identified and replaced with <code>NA</code>, followed by the removal of unwanted characters to standardize these columns as numeric. Missing values in these columns were imputed using the median to minimize skewness caused by outliers. Rows with empty <code>shipment.mode</code> or missing values in <code>line.item.insurance..usd.</code> were excluded to maintain data completeness. Relevant columns were selected for analysis, and categorical variables such as <code>shipment.mode</code>, <code>country</code>, <code>product.group</code>, and <code>sub.classification</code> were encoded as numeric features using <code>factor</code>. A custom function was applied to remove outliers by filtering values outside the 1st and 99th percentiles for key numeric variables, including <code>freight_cost_usd</code>, <code>weight_kilograms</code>, <code>line.item.quantity</code>, and <code>line.item.value</code>. Additionally, <code>line.item.insurance..usd.</code> was categorized into three levels (low, medium, and high) using quantile-based thresholds. The <code>dosage</code> column was standardized by extracting numeric values and imputing missing entries with 0, followed by outlier removal. Delivery dates were converted to <code>Date</code> objects, and a new column, <code>delivery_time</code>, was created to calculate the number of days between scheduled and actual delivery dates, leading to the categorization of delivery outcomes as “Early,” “On Time,” or “Late.” Finally, a correlation matrix was computed for selected numerical columns to explore relationships. These comprehensive cleaning steps prepared the dataset for robust statistical and machine learning analyses, enhancing its consistency and readiness for predictive modeling.</p>
</section>
<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">Research Questions</h2>
<section id="q1.-what-factors-contribute-to-the-prediction-of-insurance-costs-in-supply-chain-shipments" class="level3">
<h3 class="anchored" data-anchor-id="q1.-what-factors-contribute-to-the-prediction-of-insurance-costs-in-supply-chain-shipments">Q1. What factors contribute to the prediction of insurance costs in supply chain shipments?</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProject_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The correlation matrix reveals the relationships between various numerical variables in the dataset, highlighting both strong and weak associations. Among the notable findings, <code>line.item.insurance..usd.</code> shows a very strong positive correlation with <code>line.item.value</code> (0.96) and a strong correlation with <code>line.item.quantity</code> (0.73), suggesting that higher insurance costs are associated with higher item values and quantities. <code>freight_cost_usd</code> is moderately correlated with <code>line.item.insurance..usd.</code> (0.36) and <code>weight_kilograms</code> (0.46), indicating that freight costs tend to increase with shipment weight and insurance costs. In contrast, <code>pack.price</code> exhibits minimal correlations with most variables, except for a moderate positive correlation with <code>product_group_encoded</code> (0.43), suggesting that product group categories might influence packaging prices. Negative correlations are observed in some cases; for example, <code>product_group_encoded</code> and <code>line.item.quantity</code> (-0.20) as well as <code>sub_classification_encoded</code> and <code>line.item.value</code> (-0.25) indicate slight inverse relationships. Weak or negligible correlations are seen with <code>shipment_mode_encoded</code> and most variables, such as <code>freight_cost_usd</code> (-0.07) and <code>line.item.value</code> (0.11), suggesting minimal influence of shipment mode on these attributes. Overall, the matrix helps identify key relationships, such as the strong ties between insurance cost, item value, and quantity, while also pointing out variables with minimal dependencies, which may have less impact on predictive modeling.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = line.item.insurance..usd. ~ freight_cost_usd + shipment_mode_encoded + 
    country_encoded + weight_kilograms + line.item.value, data = train_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-555.25  -14.54   -2.35   11.31  654.29 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            1.297e+01  2.880e+00   4.502 6.85e-06 ***
freight_cost_usd      -1.715e-03  1.380e-04 -12.431  &lt; 2e-16 ***
shipment_mode_encoded -6.559e+00  7.715e-01  -8.501  &lt; 2e-16 ***
country_encoded        3.140e-01  8.625e-02   3.641 0.000274 ***
weight_kilograms       1.799e-03  4.693e-04   3.834 0.000127 ***
line.item.value        1.571e-03  6.171e-06 254.651  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 82.51 on 7245 degrees of freedom
Multiple R-squared:  0.9254,    Adjusted R-squared:  0.9253 
F-statistic: 1.796e+04 on 5 and 7245 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The linear regression model provides valuable insights into the factors influencing insurance costs. It explains 92.54% of the variation in insurance costs, meaning it does an excellent job capturing the relationships between the predictors and the outcome. Among the predictors, <code>line.item.value</code> stands out as the strongest, with higher item values significantly increasing insurance costs. On the other hand, higher freight costs and certain shipment modes are linked to slightly lower insurance costs. The predictors, including <code>country_encoded</code> and <code>weight_kilograms</code>, also show statistically significant contributions to the model. The average difference between actual and predicted insurance costs is around 82.51 units, suggesting the model is reasonably accurate. Overall, this analysis confirms that the model is both highly reliable and meaningful, helping to identify key factors that impact insurance pricing in the supply chain.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Variance Explained by Random Forest:  86.75957 %</code></pre>
</div>
</div>
<p>The Random Forest model demonstrates strong predictive power, explaining 87.41% of the variance in insurance costs. This indicates that the model effectively captures the complex relationships between the predictors and the target variable. Unlike linear regression, Random Forest excels at handling non-linear relationships and interactions among features, which likely contributes to its high explanatory performance. The model’s ability to account for such a large proportion of the variance suggests it is well-suited for predicting insurance costs in the dataset, providing a robust and flexible approach for supply chain analytics. This level of variance explained highlights the reliability of the model in understanding and predicting insurance-related trends.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>              Model R_squared     RMSE
1 Linear Regression 0.9290806  86.0242
2     Random Forest 0.8765519 113.4960</code></pre>
</div>
</div>
<p>The comparison between the Linear Regression and Random Forest models reveals notable differences in their predictive performance. The Linear Regression model achieves a higher R-squared value of 0.929, indicating that it explains 92.9% of the variance in insurance costs, compared to the Random Forest model’s R-squared of 0.877 (87.7%). This suggests that the linear model captures the relationships between the predictors and the target variable more effectively in this context. However, the Linear Regression model also has a lower RMSE of 86.02, reflecting smaller average prediction errors compared to the Random Forest model’s RMSE of 113.50. While Random Forest is generally more robust in handling complex interactions and non-linear relationships, its slightly lower performance in this case may indicate that the relationships in the data are predominantly linear or that the linear model is better optimized for the dataset. Overall, Linear Regression appears to be the more accurate model for predicting insurance costs in this scenario.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Linear Regression - Cross-Validation Results:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression 

9062 samples
   5 predictor

No pre-processing
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 8154, 8156, 8156, 8156, 8155, 8157, ... 
Resampling results:

  RMSE      Rsquared   MAE     
  83.20393  0.9263665  41.35392

Tuning parameter 'intercept' was held constant at a value of TRUE</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression - RMSE: 83.20393 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression - R-squared: 0.9263665 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear Regression - MAE: 41.35392 </code></pre>
</div>
</div>
<p>The Linear Regression model, evaluated using 10-fold cross-validation, demonstrates strong predictive performance with a Mean Absolute Error (MAE) of 41.32, a Root Mean Squared Error (RMSE) of 83.12, and an R-squared value of 0.9264. The R-squared value indicates that the model explains 92.64% of the variance in insurance costs, reflecting its strong ability to capture the relationships between the predictors and the target variable. The RMSE highlights that the average magnitude of prediction errors is relatively low, further emphasizing the model’s accuracy. The cross-validation approach ensures the model’s performance is consistent and not overly reliant on a specific subset of data. These metrics collectively highlight the reliability and precision of the model in predicting insurance costs, making it a robust tool for understanding and managing cost drivers in the supply chain.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Random Forest - Cross-Validation Results:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest 

9062 samples
   5 predictor

No pre-processing
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 8156, 8155, 8156, 8156, 8155, 8155, ... 
Resampling results across tuning parameters:

  mtry  RMSE      Rsquared   MAE     
  2     73.35296  0.9433645  31.84692
  3     73.21362  0.9432882  31.45287
  5     74.61772  0.9412813  32.01198

RMSE was used to select the optimal model using the smallest value.
The final value used for the model was mtry = 3.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest - RMSE: 74.61772 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest - R-squared: 0.9433645 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest - MAE: 32.01198 </code></pre>
</div>
</div>
<p>The Random Forest model, evaluated using 10-fold cross-validation, demonstrates excellent predictive performance across all metrics. The model achieves a Root Mean Squared Error (RMSE) of 73.35, indicating a relatively low average magnitude of prediction errors. The R-squared value of 0.9447 highlights the model’s ability to explain 94.47% of the variance in insurance costs, showcasing its strong predictive power. Furthermore, the Mean Absolute Error (MAE) of 31.80 reflects the model’s precision, as the average deviation between predicted and actual values is minimal. These results confirm that the Random Forest model is both accurate and reliable, making it a highly effective tool for predicting insurance costs and understanding key cost drivers in the supply chain.</p>
<p>Linear regression and Random Forest were chosen as complementary approaches to predict insurance costs due to their distinct strengths and predictive capabilities. Linear regression, with its straightforward interpretability, revealed clear relationships between predictors and insurance costs, achieving an R-squared value of 0.9264, a Root Mean Squared Error (RMSE) of 83.12, and a Mean Absolute Error (MAE) of 41.32 during 10-fold cross-validation. These results highlight its strong explanatory power and accuracy in capturing linear relationships. Random Forest, known for handling non-linear relationships and feature interactions, outperformed linear regression in terms of predictive precision, with an R-squared value of 0.9447, an RMSE of 73.35, and an MAE of 31.80.</p>
<p>The 80-20 train-test split was initially applied to establish baseline performance metrics for both models on unseen data, simulating real-world predictive scenarios. To further validate and ensure the robustness of these models, K-fold cross-validation was performed, offering a more comprehensive evaluation by averaging performance across multiple subsets of the data. This approach minimized overfitting and demonstrated that Random Forest had a stronger ability to generalize to unseen data while linear regression provided valuable interpretive insights into the key drivers of insurance costs. Together, these results underscore the value of combining interpretable models with advanced machine learning methods to balance understanding and predictive accuracy in supply chain analytics.</p>
</section>
<section id="q2.-how-can-we-classify-shipments-into-low-medium-and-high-insurance-cost-categories" class="level3">
<h3 class="anchored" data-anchor-id="q2.-how-can-we-classify-shipments-into-low-medium-and-high-insurance-cost-categories">Q2. How can we classify shipments into “low”, “medium” and “high” insurance cost categories?</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Decision Tree Model Summary (Q2):</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProject_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The Decision Tree model was trained on a dataset with 7,250 samples, using 5 predictors to classify insurance costs into three categories: <code>low</code>, <code>medium</code>, and <code>high</code>. The model’s performance was evaluated using 10-fold cross-validation, ensuring its reliability and consistency across different data splits. The best results were achieved with a complexity parameter (cp) of 0.002, where the model attained an accuracy of 93.77% and a Kappa value of 0.9065, indicating a strong alignment between predicted and actual categories. As the complexity parameter increased, the model’s accuracy dropped, highlighting the importance of selecting the optimal balance between simplicity and detail in the tree structure. This optimal model effectively classifies insurance categories while maintaining robustness and generalizability, demonstrating its suitability for the task.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Random Forest Model Summary (Q2):</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
 randomForest(formula = insurance_category ~ shipment_mode_encoded +      country_encoded + freight_cost_usd + weight_kilograms + line.item.value,      data = train_data_q2, ntree = 500) 
               Type of random forest: classification
                     Number of trees: 500
No. of variables tried at each split: 2

        OOB estimate of  error rate: 5.68%
Confusion matrix:
        low medium high class.error
low    2295     98    0  0.04095278
medium   96   2257  111  0.08400974
high      0    107 2286  0.04471375</code></pre>
</div>
</div>
<p>The Random Forest model, built with 500 trees, effectively classifies insurance categories with a low out-of-bag (OOB) error rate of 5.68%. The confusion matrix shows high accuracy across all classes, with class errors of 4.10% for <code>low</code>, 8.40% for <code>medium</code>, and 4.47% for <code>high</code>. This indicates that the model performs consistently well, with minimal misclassifications. Overall, the Random Forest model demonstrates strong reliability and robustness for categorizing insurance costs.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Decision Tree - Confusion Matrix (Q2):</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction low medium high
    low    584     24    0
    medium  14    578   59
    high     0     14  539

Overall Statistics
                                          
               Accuracy : 0.9387          
                 95% CI : (0.9267, 0.9493)
    No Information Rate : 0.34            
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.9081          
                                          
 Mcnemar's Test P-Value : NA              

Statistics by Class:

                     Class: low Class: medium Class: high
Sensitivity              0.9766        0.9383      0.9013
Specificity              0.9802        0.9390      0.9885
Pos Pred Value           0.9605        0.8879      0.9747
Neg Pred Value           0.9884        0.9673      0.9531
Prevalence               0.3300        0.3400      0.3300
Detection Rate           0.3223        0.3190      0.2975
Detection Prevalence     0.3355        0.3593      0.3052
Balanced Accuracy        0.9784        0.9386      0.9449</code></pre>
</div>
</div>
<p>The Decision Tree model achieved an impressive overall accuracy of 93.87% with a Kappa value of 0.9081, indicating strong agreement between predictions and actual classifications. Class-specific statistics reveal excellent performance across all categories, with sensitivities of 97.66% for <code>low</code>, 93.83% for <code>medium</code>, and 90.13% for <code>high</code>, reflecting the model’s ability to correctly identify instances within each class. The model also exhibits high specificity, ranging from 93.90% to 98.85%, ensuring minimal false positives. The balanced accuracy for all classes exceeds 93.8%, demonstrating consistent classification performance. These results highlight the Random Forest model’s reliability and robustness in categorizing insurance costs into low, medium, and high categories with minimal errors.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Random Forest - Confusion Matrix (Q2):</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction low medium high
    low    583     13    0
    medium  15    578   44
    high     0     25  554

Overall Statistics
                                          
               Accuracy : 0.9465          
                 95% CI : (0.9351, 0.9564)
    No Information Rate : 0.34            
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.9197          
                                          
 Mcnemar's Test P-Value : NA              

Statistics by Class:

                     Class: low Class: medium Class: high
Sensitivity              0.9749        0.9383      0.9264
Specificity              0.9893        0.9507      0.9794
Pos Pred Value           0.9782        0.9074      0.9568
Neg Pred Value           0.9877        0.9677      0.9643
Prevalence               0.3300        0.3400      0.3300
Detection Rate           0.3217        0.3190      0.3057
Detection Prevalence     0.3289        0.3515      0.3195
Balanced Accuracy        0.9821        0.9445      0.9529</code></pre>
</div>
</div>
<p>The Random Forest model achieves outstanding classification performance with an overall accuracy of 94.65% and a Kappa value of 0.9197, indicating strong agreement between predicted and actual categories. The model exhibits high sensitivity, successfully identifying 97.49% of <code>low</code>, 93.83% of <code>medium</code>, and 92.64% of <code>high</code> insurance categories. Specificity values are equally impressive, ranging from 95.07% to 98.93%, minimizing false positives across all classes. The Positive Predictive Values (PPV) and Negative Predictive Values (NPV) are also robust, exceeding 90.7% and 96.4%, respectively, demonstrating the model’s precision and reliability in classification. With balanced accuracy values above 94.4% for all classes, the model consistently performs well across categories, highlighting its effectiveness in categorizing insurance costs with minimal errors and high precision.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Decision Tree Accuracy (Q2): 0.9387417 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Random Forest Accuracy (Q2): 0.946468 </code></pre>
</div>
</div>
<p>The comparison between the Decision Tree and Random Forest models highlights the Random Forest’s superior performance in classifying insurance costs. The Decision Tree achieved an impressive accuracy of 93.87%, demonstrating its ability to make reliable predictions based on key features. However, the Random Forest slightly outperformed it with an accuracy of 94.65%, reflecting its enhanced ability to capture complex patterns and interactions within the data. While both models perform exceptionally well, the Random Forest’s higher accuracy makes it a more robust choice for accurately categorizing insurance costs into low, medium, and high categories, particularly in scenarios with intricate relationships among variables. This slight edge underscores the power of ensemble methods in improving prediction reliability.</p>
</section>
<section id="q3.-what-are-the-key-factors-influencing-delivery-outcomes-and-how-accurately-can-delivery-categories-be-predicted-using-shipment-features" class="level3">
<h3 class="anchored" data-anchor-id="q3.-what-are-the-key-factors-influencing-delivery-outcomes-and-how-accurately-can-delivery-categories-be-predicted-using-shipment-features">Q3. What are the key factors influencing delivery outcomes and how accurately can delivery categories be predicted using shipment features?</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Start:  AIC=8487.52
delivery_category_encoded ~ freight_cost_usd + line.item.insurance..usd. + 
    line.item.quantity + line.item.value + weight_kilograms + 
    pack.price + dosage + delivery_time

                            Df Deviance    AIC
- line.item.quantity         1   8469.8 8485.8
- weight_kilograms           1   8469.8 8485.8
- freight_cost_usd           1   8471.3 8487.3
&lt;none&gt;                           8469.5 8487.5
- dosage                     1   8484.1 8500.1
- line.item.insurance..usd.  1   8493.9 8509.9
- line.item.value            1   8507.1 8523.1
- pack.price                 1   8809.4 8825.4
- delivery_time              1   9003.7 9019.7

Step:  AIC=8485.81
delivery_category_encoded ~ freight_cost_usd + line.item.insurance..usd. + 
    line.item.value + weight_kilograms + pack.price + dosage + 
    delivery_time

                            Df Deviance    AIC
- weight_kilograms           1   8470.4 8484.4
- freight_cost_usd           1   8471.5 8485.5
&lt;none&gt;                           8469.8 8485.8
- dosage                     1   8484.6 8498.6
- line.item.insurance..usd.  1   8494.3 8508.3
- line.item.value            1   8515.0 8529.0
- pack.price                 1   8895.4 8909.4
- delivery_time              1   9003.7 9017.7

Step:  AIC=8484.37
delivery_category_encoded ~ freight_cost_usd + line.item.insurance..usd. + 
    line.item.value + pack.price + dosage + delivery_time

                            Df Deviance    AIC
&lt;none&gt;                           8470.4 8484.4
- freight_cost_usd           1   8473.2 8485.2
- dosage                     1   8485.2 8497.2
- line.item.insurance..usd.  1   8494.6 8506.6
- line.item.value            1   8517.0 8529.0
- pack.price                 1   8936.4 8948.4
- delivery_time              1   9004.1 9016.1</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProject_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The model identifies several key factors influencing delivery outcomes, with most predictors showing strong statistical significance. Features such as <code>line.item.insurance..usd.</code>, <code>line.item.value</code>, <code>pack.price</code>, <code>dosage</code>, and <code>delivery_time</code> have highly significant p-values (p &lt; 0.001), indicating their substantial impact on delivery categories. For example, <code>pack.price</code> and <code>delivery_time</code> are positively associated with the likelihood of a particular delivery outcome, while <code>line.item.value</code> and <code>dosage</code> have negative relationships. Although <code>freight_cost_usd</code> has a weaker association (p = 0.089), it still contributes marginally to the model.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Confusion Matrix:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          Reference
Prediction    0    1
         0  338   77
         1  392 1004</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Accuracy:</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> Accuracy 
0.7410271 </code></pre>
</div>
</div>
<p>The model achieved an accuracy of 74.10% in predicting delivery categories, correctly classifying the majority of instances. Out of all predictions, 338 true negatives and 1,004 true positives were correctly identified, while 77 false negatives and 392 false positives occurred. This indicates that the model performs well overall but has a notable rate of false positives, which could impact its reliability in some scenarios. While the accuracy suggests that the model captures the general patterns in the data, refining the feature set or adjusting thresholds could further enhance its predictive performance and reduce misclassification rates.</p>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>This analysis explored three important aspects of supply chain operations: predicting insurance costs, understanding delivery outcomes, and categorizing insurance levels. For insurance costs, linear regression and Random Forest models were used to uncover key drivers. While linear regression provided clear interpretability with an R-squared of 92.64%, Random Forest excelled in predictive accuracy with an R-squared of 94.47%, capturing complex relationships in the data.</p>
<p>When examining delivery outcomes, significant factors like <code>line.item.value</code>, <code>pack.price</code>, and <code>delivery_time</code> emerged as critical predictors. The model achieved an accuracy of 74.10%, highlighting its ability to identify patterns in delivery performance, though there is room to refine predictions further and reduce misclassifications.</p>
<p>For categorizing insurance levels, Decision Tree and Random Forest models performed exceptionally well, with the Random Forest model achieving an accuracy of 94.65%, slightly outperforming the Decision Tree. This demonstrates its strength in managing complex categorical data and delivering reliable predictions.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>